// This component will render a list of books. It will be a class 
// component, not functional component.

// A react component that's connected with redux is called a "smart" 
// component or container. A connection is defined as the react component has 
// direct access to the state produced by redux. A react component that does 
// not have this connection with redux and is called a "dumb" component.
// React and redux are distinct libraries and it's only through react-redux 
// that we can meld the two together.   

// Remember, if we import a word like React, we import the entire object. If
// we import something in {}, we import a single property which is a function named 
// connect.
import React, {Component} from "react";
import {connect} from "react-redux";

import {selectBook} from "../actions/index";

// This is a redux function that makes sure the action generated by the action creator 
// actually ends up flowing through all the reducers. 
import {bindActionCreators} from "redux";

// This class component creates an ul tag and calls a helper function. 
class BookList extends Component {
  // This function maps over an array of books passed in from props. For each book in
  // the array, create an li tag that contains the book title. Make the book title the 
  // unique identifier key as well. To select a particular book, we add a click handler 
  // that uses the returned selectBook action creator from our mapDispatchToProps(). 
  renderList() {
    return this.props.books.map((book) => {
      return (
        <li 
          key={book.title}
          onClick={() => this.props.selectBook(book)} 
          className="list-group-item">
            {book.title}
        </li>
      );
    });
  }

  render() {
    return (
      <ul className="list-group col-sm-4">
        {this.renderList()}
      </ul>
    );
  }
}

// The purpose of this function is to take our application state as an argument 
// (the app state comprises of our list of books and our selected book) and 
// whatever is returned will show up as props inside BookList.
// This function is the glue that holds binds react and redux.
// Whenever the state from redux changes, the returned object with books property 
// will change and this BookList container will automatically re-render. 
function mapStateToProps(state) {
  // Usually an object is returned. Whatever's inside will be set to this.props 
  // in our component. The value of state.books is the array of books from our 
  // Redux reducer_books.js and it's assigned to the key of books, which BookList 
  // component will return with this.props.book.map(). 
  return {
    books: state.books
  };
}

// Anything returned from this function will end up as props on the BookList container.
function mapDispatchToProps(dispatch) {
  // The object property selectBook has a value of selectBook. This value is the 
  // actual action creator selectBook that we imported at the top. Whenever 
  // selectBook is called, the result should be passed to all of our reducers. 
  // Dispatch receives the actions like a funnel and spits them back out to all 
  // reducers. 
  return bindActionCreators({selectBook: selectBook}, dispatch);
}

// This connect function from react-redux contributes to the merging of react and redux.
// It takes functions (mapStateToProps, mapDispatchToProps) and a component (BookList) and 
// produces a container. A container is a react component that's aware of state contained 
// in redux. Connect needs to know about this new dispatch method with its bound action 
// creator, selectBook, and make it available as a prop to this container.  
export default connect(mapStateToProps, mapDispatchToProps)(BookList);














